In [1]:
import numpy as np

### Задание 1 

In [16]:
x = np.arange(0, 10)

In [17]:
np.argsort(-x)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2

In [6]:
my_matrix = np.diag(np.arange(2, 50, 15))
my_matrix

array([[ 2,  0,  0,  0],
       [ 0, 17,  0,  0],
       [ 0,  0, 32,  0],
       [ 0,  0,  0, 47]])

In [7]:
sum([row[index] for index, row in enumerate(my_matrix)])

98

### Задание 3 

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [2]:
from numpy import linalg

In [20]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [21]:
b = np.array( [4, 12, -3] )

In [22]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [23]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

### Задание 4

In [3]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

In [21]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [24]:
def cosine_function(users_stats, next_user_stats):
    """
    Подсчет косинуса угла между векторами users_stats, next_user_stats по их координатам
    """
    res = []

    bLength = np.linalg.norm(next_user_stats)
   
    for users in users_stats:  
    
        aLength = np.linalg.norm(users)  
        
        cosine = np.dot(users, next_user_stats) / (aLength *  bLength) 
        
        res.append(cosine)
        
        user = res.index(max(res))
        
    print(f'Максимальное схожесть у покупателя: {user+1}')          

In [25]:
cosine_function (users_stats, next_user_stats)

Максимальное схожесть у покупателя: 8
